// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGS3lGz6lfuO0rh12aZ7LFhT_G0M1wkm4',
    appId: '1:239976219488:web:d82ea80a67b11c282ad405',
    messagingSenderId: '239976219488',
    projectId: 'heytheo-21eb2',
    authDomain: 'heytheo-21eb2.firebaseapp.com',
    storageBucket: 'heytheo-21eb2.firebasestorage.app',
    measurementId: 'G-JYNE5DHZMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp814zx2J4exkUxesp86j65By9gvU-LEY',
    appId: '1:239976219488:android:60efc803ca656d982ad405',
    messagingSenderId: '239976219488',
    projectId: 'heytheo-21eb2',
    storageBucket: 'heytheo-21eb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSFhRR750BNkttfUcZvASuR7MQ-W-kWw',
    appId: '1:239976219488:ios:c2d35b1ed17821812ad405',
    messagingSenderId: '239976219488',
    projectId: 'heytheo-21eb2',
    storageBucket: 'heytheo-21eb2.firebasestorage.app',
    iosBundleId: 'com.example.heytheo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuSFhRR750BNkttfUcZvASuR7MQ-W-kWw',
    appId: '1:239976219488:ios:c2d35b1ed17821812ad405',
    messagingSenderId: '239976219488',
    projectId: 'heytheo-21eb2',
    storageBucket: 'heytheo-21eb2.firebasestorage.app',
    iosBundleId: 'com.example.heytheo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGS3lGz6lfuO0rh12aZ7LFhT_G0M1wkm4',
    appId: '1:239976219488:web:bd36d39a00373d322ad405',
    messagingSenderId: '239976219488',
    projectId: 'heytheo-21eb2',
    authDomain: 'heytheo-21eb2.firebaseapp.com',
    storageBucket: 'heytheo-21eb2.firebasestorage.app',
    measurementId: 'G-SBK9HGLWR6',
  );
}
